pipeline {
   agent any

   tools {
      // Install the Maven version configured as "Maven2" and add it to the path.
      maven "Maven2"
   }

   stages {
      stage('Clone Repo') { 
            steps {
                sh "rm -rf simple-java-maven-app"
                sh "git clone https://github.com/vinay81saini/simple-java-maven-app.git"
                sh "mvn clean -f simple-java-maven-app"
                //use bat for windows
            }
        }
        stage('Test') { 
            steps {
                sh "mvn test -f simple-java-maven-app"
            }
        }
        stage('Deploy') { 
            steps {
                sh "mvn package -f simple-java-maven-app"

            
         }
      }
   }
}
